openapi: "3.0.3"
info:
  title: "🍽️API Comanda: Ejemplo de especificación"
  version: "1.0.0"
  description: '[UPM] AOS: API para la gestión de Comandas'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  contact:
    name: Máster Universitario en Ingeniería Web
    url: 'http://miw.etsisi.upm.es/'
    email: miw.etsisi@upm.es
servers:
  - url: '{schema}://{server}:{port}/{basePath}'
    description: Servidor local
    variables:
      schema:
        description: Esquema
        default: http
        enum:
          - http
          - https
      server:
        description: Nombre del servidor
        default: 127.0.0.1
      port:
        description: Número de puerto
        default: '80'
      basePath:
        description: Ruta base
        default: api/v1
tags:
  - name: '👆 Comanda'
    description: Comanda de un usuario registrado
  - name: '🧾 Factura'
    description: Factura con el conjunto de comandas de un usuario
paths:
  /comanda:
    get:
      tags:
        - '👆 Comanda'
      summary: Obtiene todas las comandas de un usuario
      operationId: upm_aos_comanda_cget
      responses:
        200:
          description: Array de comandas
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                type: object
                properties:
                  comandas:
                    description: array de comandas
                    type: array
                    items:
                      $ref: '#/components/schemas/Comanda'
              examples:
                comandasExamples:
                  $ref: '#/components/examples/comandas'
        404:
          $ref: '#/components/responses/Response_404'
    post:
      tags:
        - '👆 Comanda'
      summary: Crea una nueva comanda
      description: Genera una nueva comanda para un usuario previamente registrado
      operationId: upm_aos_comanda_post
      requestBody:
        $ref: '#/components/requestBodies/comandaRB'
      responses:
        201:
          description: comanda creada
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comanda'
        422:
          $ref: '#/components/responses/Response_422'
    options:
      tags:
        - '👆 Comanda'
      summary: Proporciona la lista de los métodos HTTP soportados.
      description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
      operationId: upm_aos_comanda_coptions
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'

  '/comanda/{comandaId}':
    parameters:
      - $ref: '#/components/parameters/comandaId'
    get:
      tags:
        - '👆 Comanda'
      summary: Recupera una comanda específica identificada por su ID.
      description: Devuelve la comanda identificada por `comandaId`.
      operationId: upm_aos_comanda_get
      responses:
        '200':
          description: Comanda
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comanda'
        '404':
          $ref: '#/components/responses/Response_404'
    delete:
      tags:
        - '👆 Comanda'
      summary: Elimina una comanda.
      description: Elimina la comanda identificada por `comandaId`.
      operationId: upm_aos_comanda_delete
      responses:
        '204':
          description: Comanda eliminada &lt;Cuerpo de la respuesta vacío&gt;
        '404':
          $ref: '#/components/responses/Response_404'
    options:
      tags:
        - '👆 Comanda'
      summary: Proporciona la lista de los métodos HTTP soportados.
      description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
      operationId: upm_aos_comanda_options
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'
    put:
      tags:
        - '👆 Comanda'
      summary: Modifica la comanda.
      description: Actualiza la comanda identificada por `comandaId`.
      operationId: upm_aos_comanda_put
      parameters:
        - $ref: '#/components/parameters/ifMatchParam'
      requestBody:
        $ref: '#/components/requestBodies/comandaRB'
      responses:
        '200':
          description: '`OK`: la comanda ha sido modificada'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comanda'
        '404':
          $ref: '#/components/responses/Response_404'
        '412':
          $ref: '#/components/responses/Response_412'

  /factura:
    post:
      tags: [ '🧾 Factura' ]
      summary: Genera la factura de un usuario
      description: Genera la factura de un usuario previamente identificado.
      operationId: upm_aos_factura_post
      # requestBody:
      #  description: El cuerpo de la petición está vacío
      responses:
        '201':
          description: Factura
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          $ref: '#/components/responses/Response_404'
  /factura/{facturaId}:
    parameters:
      - $ref: '#/components/parameters/facturaId'
    get:
      tags: [ '🧾 Factura' ]
      summary: Obtiene una factura
      description: Obtiene una factura identificada por su facturaID.
      operationId: upm_aos_factura_get
      responses:
        '200':
          description: Factura
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          $ref: '#/components/responses/Response_404'

#
# Definición de Componentes
#
components:

  schemas:
    Comanda:
      $ref: './schemas/Comanda.yaml#/Comanda'
    Factura:
      $ref: './schemas/Factura.yaml#/Factura'
    HTTP_Problem:
      $ref: './schemas/HTTP_Problem.yaml#/HTTP_Problem'

  headers:
    ETag:
      description: Entity Tag (identificador único proporcionado para validación de caché)
      schema:
        type: string
        pattern: "[0-9a-f]*"
        # https://github.com/marak/Faker.js#api-methods
        x-faker: random.uuid
        example:
          33a64df551425fcc
    Location:
      description: '`URI` del nuevo recurso'
      schema:
        type: string
        format: url
        x-faker: internet.url
        example:
          /api/v1/comanda/1936
    Allow:
      description: Lista de métodos HTTP soportados
      schema:
        type: string
      example:
        GET,DELETE,PUT,OPTIONS

  parameters:
    comandaId:
      name: comandaId
      in: path
      description: ID de la comanda
      required: true
      schema:
        type: integer
        pattern: ^\d+$
    facturaId:
      name: facturaId
      in: path
      description: ID de la factura
      required: true
      schema:
        type: integer
        pattern: ^\d+$
    ifMatchParam:
      name: If-Match
      in: header
      description: ETag del recurso que se desea modificar
      required: true
      schema:
        type: string
        pattern: "[0-9a-f]*"

  requestBodies:
    comandaRB:
      description: '`Comanda` data'
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - ref
              - unidades
            properties:
              # userId:
              #   description: user Id
              #   type: integer
              #   format: int32
              ref:
                description: Ref. del artículo solicitado
                type: integer
                format: int32
              unidades:
                description: Número de unidades de la referencia
                type: integer
                format: int32
                minimum: 1
            example:
              # userId: 2030
              ref: 33
              unidades: 12

  responses:
    Response_404:
      description: '`NOT FOUND`: recurso no disponible'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-404:
              $ref: '#/components/examples/response-http-404'
    Response_412:
      description: '`PRECONDITION FAILED`: no se cumple alguna condición previa'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-412:
              $ref: '#/components/examples/response-http-412'
    Response_422:
      description: '`UNPROCESSABLE ENTITY`: falta la referencia o las unidades'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-422:
              $ref: '#/components/examples/response-http-422'

  examples:
    comandas:
      value:
        - id: 2021
          userId: 34
          ref: 1909
          unidades: 2
          links:
            parent:
              href: /api/v1/comanda
              rel: listaComandas
            self:
              href: /api/v1/comanda/2021
              rel: modificar cancelar
            factura:
              href: /api/v1/factura
              rel: pedirFactura
        - id: 2222
          userId: 34
          ref: 22222222
          unidades: 4
          links:
            parent:
              href: /api/v1/comanda
              rel: listaComandas
            self:
              href: /api/v1/comanda/2222
              rel: modificar cancelar
            factura:
              href: /api/v1/factura
              rel: pedirFactura
    response-http-404:
      value:
        type: https://httpstatuses.com/404
        title: NOT FOUND
        status: 404
        detail: El recurso solicitado no está disponible...
        instance: about:blank
    response-http-412:
      value:
        type: https://httpstatuses.com/412
        title: PRECONDITION FAILED
        status: 412
        detail: No se cumple alguna condición previa...
        instance: about:blank
    response-http-422:
      value:
        type: https://httpstatuses.com/422
        title: UNPROCESSABLE ENTITY
        status: 422
        detail: Falta la referencia o las unidades...
        instance: about:blank
